# .github/workflows/main.yml
name: Run Script

on:
  workflow_dispatch:

jobs:
  run-script-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiofiles asyncio

      - name: Run main script
        run: |
          python grab_mayhemids.py

      - name: Run main script
        run: |
          python update.py

      - name: Commit and push changes
        if: success()  # Only run this step if the previous steps were successful
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add .
          git commit -m "Updated mayhemid's listings as of $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger workflow on main branch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
